@echo off
title Ejercicio 5 Menu de ecuaciones
ECHO.
SET /P NUM1= ESCRIBE UN VALOR NUMERICO 
SET /P NUM2= ESCRIBE OTRO VALOR NUMERICO 
:MENU
ECHO.
ECHO ....................................................................
ECHO PRESIONA +, -, * O / PARA SELECCIONAR UNA ECUACION, O EXIT PARA SALIR
ECHO ....................................................................
ECHO.
ECHO + = ES SUMA
ECHO - = ES RESTA
ECHO * = ES MULTIPLICACION
ECHO / = ES DIVISION
ECHO.
SET /P E= ESCRIBE +, -, *, / O EXIT Y LUEGO PRESIONA ENTER: 
IF %E%==+ GOTO PLUS
IF %E%==- GOTO LESS
IF %E%==* GOTO MULT
IF %E%==/ GOTO DIVI
IF %E%==EXIT GOTO SALIDA
:PLUS
SET /A SUM=%NUM1%+%NUM2%
ECHO LA RESPUESTA ES %SUM%
PAUSE
ECHO.
ECHO ¿QUIERES VOLVER A REALIZAR OTRA OPREACION?
ECHO.
ECHO ........................................
ECHO PRESIONA Y O N PARA RESPONDER LA PREGUNTA
ECHO ........................................
ECHO.
ECHO Y - ES SI
ECHO N - ES NO
ECHO.
SET /P M= ESCRIBE Y O N Y LUEGO PRESIONA ENTER: 
IF %M$==Y GOTO SI
IF %M%==N GOTO NO
:SI
GOTO MENU

:LESS
SET /A REST=%NUM1%-%NUM2%
ECHO LA RESPUESTA ES %REST%
PAUSE
ECHO.
ECHO ¿QUIERES VOLVER A REALIZAR OTRA OPREACION?
ECHO.
ECHO ........................................
ECHO PRESIONA Y O N PARA RESPONDER LA PREGUNTA
ECHO ........................................
ECHO.
ECHO Y - ES SI
ECHO N - ES NO
ECHO.
SET /P M= ESCRIBE Y O N Y LUEGO PRESIONA ENTER: 
IF %M$==Y GOTO SI
IF %M%==N GOTO NO
:SI
GOTO MENU

:MULT
SET /A MULTI=%NUM1%*%NUM2%
ECHO LA RESPUESTA ES %MULTI%
PAUSE
ECHO.
ECHO ¿QUIERES VOLVER A REALIZAR OTRA OPREACION?
ECHO.
ECHO ........................................
ECHO PRESIONA Y O N PARA RESPONDER LA PREGUNTA
ECHO ........................................
ECHO.
ECHO Y - ES SI
ECHO N - ES NO
ECHO.
SET /P M= ESCRIBE Y O N Y LUEGO PRESIONA ENTER: 
IF %M$==Y GOTO SI
IF %M%==N GOTO NO
:SI
GOTO MENU

:DIVI
SET /A DIVIS=%NUM1%/%NUM2%
ECHO LA RESPUESTA ES %DIVIS%
PAUSE
ECHO.
ECHO ¿QUIERES VOLVER A REALIZAR OTRA OPREACION?
ECHO.
ECHO ........................................
ECHO PRESIONA Y O N PARA RESPONDER LA PREGUNTA
ECHO ........................................
ECHO.
ECHO Y - ES SI
ECHO N - ES NO
ECHO.
SET /P M= ESCRIBE Y O N Y LUEGO PRESIONA ENTER: 
IF %M$==Y GOTO SI
IF %M%==N GOTO NO
:SI
GOTO MENU